# Generated by Django 2.1.3 on 2018-11-08 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presufam', '0004_auto_20181025_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='income',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
